src/Entity/Evenement.php
<?php

namespace App\Entity;

use App\Repository\EvenementRepository;
use Doctrine\ORM\Mapping as ORM;


#[ORM\Entity(repositoryClass: EvenementRepository::class)]
class Evenement
{

    #[ORM\Id]
    #[ORM\GeneratedValue]// auto increment
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 10000)]

    private ?string $description = null;

    #[ORM\ManyToOne(inversedBy: 'evenements')]
    private ?CategorieEvenement $categorie=null;



    #[ORM\Column(type: 'date')]
    private ?\DateTime $date = null;

    #[ORM\ManyToOne(inversedBy: 'evenements')]
    private ?User $createur=null;

    #[ORM\Column(length: 255)]
    private ?string $localisation = null;
    #[ORM\Column(length: 255)]
    private ?string $Addresse = null;
    public function getAddresse(): ?string
    {
        return $this->Addresse;
    }
    public function setAddresse(?string $Addresse): void
    {
        $this->Addresse = $Addresse;
    }

    #[ORM\Column(type: 'boolean')]
    private ?bool $freeorpaid ;

    #[ORM\Column(type: 'boolean')]
    private ?bool $online ;

    #[ORM\Column(length: 255)]
    private ?string $link = null;




    public function getId(): ?int
    {
        return $this->id;
    }


    public function getNom(): ?string
    {
        return $this->nom;
    }


    public function setNom(?string $nom): void
    {
        $this->nom = $nom;
    }


    public function getDescription(): ?string
    {
        return $this->description;
    }


    public function setDescription(?string $description): void
    {
        $this->description = $description;
    }


    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }


    public function setDate(?\DateTimeInterface $date): void
    {
        $this->date = $date;
    }


    public function getcreateur(): ?User
    {
        return $this->createur;
    }


    public function setCreateur(?User $createur): void
    {
        $this->createur = $createur;
    }


    public function getLocalisation(): ?string
    {
        return $this->localisation;
    }

    public function setLocalisation(?string $localisation): void
    {
        $this->localisation = $localisation;
    }

    /**
     * @return bool|null
     */
    public function getFreeorpaid(): ?bool
    {
        return $this->freeorpaid;
    }

    /**
     * @param bool|null $freeorpaid
     */
    public function setFreeorpaid(?bool $freeorpaid): void
    {
        $this->freeorpaid = $freeorpaid;
    }

    /**
     * @return bool|null
     */
    public function getOnline(): ?bool
    {
        return $this->online;
    }

    /**
     * @param bool|null $online
     */
    public function setOnline(?bool $online): void
    {
        $this->online = $online;
    }

    /**
     * @return string|null
     */
    public function getLink(): ?string
    {
        return $this->link;
    }

    /**
     * @param string|null $link
     */
    public function setLink(?string $link): void
    {
        $this->link = $link;
    }


    public function getCategorie(): ?CategorieEvenement
    {
        return $this->categorie;
    }


    public function setCategorie(?CategorieEvenement $categorie): void
    {
        $this->categorie = $categorie;
    }
}

src/Entity/Jaime.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\Repository\JaimeRepository;

/**
 * Jaime
 *
 * @ORM\Table(name="Jaime")
 * @ORM\Entity(repositoryClass="App\Repository\JaimeRepository")
 */
#[ORM\Entity(repositoryClass: JaimeRepository::class)]
class Jaime
{
    #[ORM\Id]
    #[ORM\GeneratedValue]// auto increment
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'jaimes')]
    private ?Evenement $Event=null;



    #[ORM\ManyToOne(inversedBy: 'jaimes')]
    private ?User $User=null;



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEvent(): ?Evenement
    {
        return $this->Event;
    }

    public function setEvent(?Evenement $Event): self
    {
        $this->Event = $Event;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }


}

src/Controller/ReservationController.php
<?php

namespace App\Controller;

use App\Entity\BilletReserver;
use App\Entity\Reservation;
use App\Form\ReservationEditType;
use App\Form\ReservationType;
use App\Repository\BilletRepository;
use App\Repository\BilletReserverRepository;
use App\Repository\EvenementRepository;
use App\Repository\ReservationRepository;
use BaconQrCode\Renderer\Image\Png;
use BaconQrCode\Writer;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/reservation')]
class ReservationController extends AbstractController
{
    #[Route('/index/', name: 'app_reservation_index', methods: ['GET'])]
    public function index($eventId, EvenementRepository $eventRepository): Response
    {
        $event = $eventRepository->find($eventId);
        return $this->render('reservation/index.html.twig', [
            'event' => $event
        ]);
    }

    #[Route('/{reservationId}/{eventId}/participate/ticket', name: 'app_ticket', methods: ['GET', 'POST'])]
    public function ticket(Request $request, $reservationId, $eventId, EvenementRepository $evenementRepository, ReservationRepository $reservationRepository, BilletRepository $billetRepository, BilletReserverRepository $billetReserverRepository): Response
    {
        $reservation = $reservationRepository->find($reservationId);
        $billets = $billetRepository->findBy(['evenement' => $eventId]);

        // Initialize an empty array to hold the BilletReserver objects
        $billetReserversByType = [];
        $qrCodeTable = [];
        //  foreach billet store the qrCideDataUri in a table named qrCodeTable and render it in the view
        foreach ($billets as $billet) {
            $billetCode = "CODE".$billet->getType().$billet->getEvenement()->getNom().$billet->getEvenement()->getcreateur()->getId().$reservation->getNom();
            $renderer = new Png();
            $renderer->setWidth(150);
            $renderer->setHeight(150);
            $writer = new Writer($renderer);
            $qrCode = $writer->writeString($billetCode);
            $qrCodeDataUri = "data:image/png;base64," . base64_encode($qrCode);
            $qrCodeTable[] = $qrCodeDataUri;
        }
        if ($request->getMethod() == 'POST') {
            // Retrieve the form data
            //if the number of tickets normalCount is more than the number of tickets available show and error message
            $normalCount = $request->request->getInt('Normal');
            $vipCount = $request->request->getInt('VIP');
            $studentCount = $request->request->getInt('Etudiant');
            // Create new BilletReserver objects for the selected ticket types
            foreach ($billets as $billet) {
                $type = $billet->getType();
                $billetReserver = new BilletReserver();
                $billetReserver->setBillet($billet);
                $billetReserver->setReservation($reservation);
                $billetReserver->setNombre(0);


                if ($type == 'Normal' and $normalCount <= $billet->getNbrBilletAvailable()) {
                    $billetReserver->setNombre($normalCount);
                    $billet->setNbrBilletAvailable($billet->getNbrBilletAvailable() - $normalCount);
                }elseif ($type == 'Normal' and $normalCount > $billet->getNbrBilletAvailable()){
                    $this->addFlash('error', 'Le nombre de billets normaux est supérieur au nombre de billets disponibles');
                    return $this->redirectToRoute('app_ticket', ['reservationId' => $reservationId, 'eventId'=>$eventId]);
                }elseif ($type == 'VIP' and $vipCount > $billet->getNbrBilletAvailable()){
                    $this->addFlash('error', 'Le nombre de billets VIP est supérieur au nombre de billets disponibles');
                    return $this->redirectToRoute('app_ticket', ['reservationId' => $reservationId, 'eventId'=>$eventId]);
                }elseif ($type == 'VIP' and $vipCount <= $billet->getNbrBilletAvailable()) {
                    $billetReserver->setNombre($vipCount);
                    $billet->setNbrBilletAvailable($billet->getNbrBilletAvailable() - $vipCount);
                } elseif ($type == 'Etudiant' and $studentCount <= $billet->getNbrBilletAvailable()) {
                    $billetReserver->setNombre($studentCount);
                }elseif ($type == 'Etudiant' and $studentCount > $billet->getNbrBilletAvailable()){
                    $this->addFlash('error', 'Le nombre de billets Etudiant est supérieur au nombre de billets disponibles');
                    return $this->redirectToRoute('app_ticket', ['reservationId' => $reservationId, 'eventId'=>$eventId]);
                }

                $billetReserversByType[$type] = $billetReserver;
            }

            // Save the new BilletReserver objects to the database
            $entityManager = $this->getDoctrine()->getManager();
            foreach ($billetReserversByType as $billetReserver) {
                $entityManager->persist($billetReserver);
            }
            $entityManager->flush();

            return $this->redirectToRoute('app_evenement_show', ['id'=>$eventId]);
        }

        return $this->render('reservation/next.html.twig', [
            'reservation' => $reservation,
            'billets'=>$billets,
            'eventId' => $eventId,
            'qrCodeTable' => $qrCodeTable,
        ]);
    }

    #[Route('/{eventId}/participate', name: 'app_reservation_new', methods: ['GET', 'POST'])]
    public function new(BilletRepository $billetRepository, $eventId,EvenementRepository $eventRepository, Request $request, ReservationRepository $reservationRepository, BilletReserverRepository $billetReserverRepository): Response
    {
        $billet= $billetRepository->findBy(['evenement' => $eventId]);
        $reservation = new Reservation();
        $event = $eventRepository->find($eventId);
        $user= $this->getUser();

        $existingReservation = $reservationRepository->createQueryBuilder('r')
            ->join('r.billetReservers', 'br')
            ->join('br.billet', 'b')
            ->andWhere('r.user = :user')
            ->andWhere('b.evenement = :evenement')
            ->setParameter('user', $user)
            ->setParameter('evenement', $event)
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();

        if ($existingReservation) {
            $this->addFlash('danger', 'Vous avez déjà une réservation pour cet événement');
            return $this->redirectToRoute('app_evenement_show',  ['id' => $eventId]);
        }

        $form = $this->createForm(ReservationType::class, $reservation,[
            'localisation-initial-value' => $event->getAddresse(),
            'date-initial-value' => $event->getDate(),
        ]);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $reservation->setUser($user);
            $reservation->setStatus('en attente');
            $reservation->setPaymentStatus('non payé');
            $reservation->setLocation($event->getAddresse());
            $reservationRepository->save($reservation, true);
            $id = $reservationRepository->find($reservation)->getId();
            return $this->redirectToRoute('app_ticket', ['reservationId'=>$id ,'eventId'=>$event->getId()], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('reservation/new.html.twig', [
            'billets' => $billet,
            'event' => $event,
            'reservation' => $reservation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_reservation_show', methods: ['GET'])]
    public function show(ReservationRepository $reservationRepository): Response
    {
        $user= $this->getUser();
        $reservations = $reservationRepository->findBy(['user' => $user]);
        return $this->render('reservation/show.html.twig', [
            'reservations' => $reservations,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_reservation_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Reservation $reservation, ReservationRepository $reservationRepository): Response
    {

        $form = $this->createForm(ReservationEditType::class, $reservation);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $reservationRepository->save($reservation, true);
            return $this->redirectToRoute('app_profil-reservation', [], Response::HTTP_SEE_OTHER);
        }
        /*dump($form->getErrors());*/
        return $this->renderForm('reservation/edit.html.twig', [
            'reservation' => $reservation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_reservation_delete', methods: ['POST'])]
    public function delete(Request $request, Reservation $reservation, ReservationRepository $reservationRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$reservation->getId(), $request->request->get('_token'))) {
            $reservationRepository->remove($reservation, true);
        }

        return $this->redirectToRoute('app_reservation_index', [], Response::HTTP_SEE_OTHER);
    }

}

templates/reservation/_form.html.twig
{{ form_start(form, {'attr': {'novalidate':'novalidate'}} ) }}
<label style="font-weight:bold; color:red;">Reservation details:</label><br>
    {{ form_label(form.dateReservation,"Reservation Date") }}
    {{ form_widget(form.dateReservation) }}
    {{ form_errors(form.dateReservation) }}
    {{ form_label(form.location) }}
    {{ form_widget(form.location)  }}
    {{ form_errors(form.location) }}<br>
<label style="font-weight:bold; color:red;">Contact informations:</label><br>
    {{ form_label(form.prenom) }}
    {{ form_widget(form.prenom) }}
    {{ form_errors(form.prenom) }}
    {{ form_label(form.nom) }}
    {{ form_widget(form.nom) }}
    {{ form_errors(form.nom) }}
    {{ form_label(form.email) }}
    {{ form_widget(form.email) }}
    {{ form_errors(form.email) }}
    {{ form_label(form.telephone) }}
    {{ form_widget(form.telephone) }}
    {{ form_errors(form.telephone) }}
    {{ form_label(form.address) }}
    {{ form_widget(form.address) }}
    {{ form_errors(form.address) }}<br>
<button class="btn my-btn">{{ button_label|default('Suivant') }}</button>

<style>
    .my-btn {
        background-color: #4CAF50;
        border: none;
        color: white;
        padding: 10px 20px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        margin: 4px 2px;
        cursor: pointer;
    }
</style>

{{ form_end(form) }}

templates/reservation/edit.html.twig
{% extends '/profil/index.html.twig' %}
{% block cardtitle %}Edit Reservation{% endblock %}
{% block content %}
<div>
    {{ form_start(form, {'attr': {'novalidate':'novalidate'}} ) }}
    {{ form_row(form._token) }}
    {{ form_errors(form) }}
    {{ form_label(form.prenom) }}
    {{ form_widget(form.prenom) }}
    {{ form_errors(form.prenom) }}
    {{ form_label(form.nom) }}
    {{ form_widget(form.nom) }}
    {{ form_errors(form.nom) }}
    {{ form_label(form.email) }}
    {{ form_widget(form.email) }}
    {{ form_errors(form.email) }}
    {{ form_label(form.telephone) }}
    {{ form_widget(form.telephone) }}
    {{ form_errors(form.telephone) }}
    {{ form_label(form.address) }}
    {{ form_widget(form.address) }}
    {{ form_errors(form.address) }}
</div>
    <button class="btn my-btn">{{ button_label|default('Enregistrer') }}</button>
    <style>
        .my-btn {
            background-color: #4CAF50;
            border: none;
            color: white;
            padding: 10px 20px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            margin: 4px 2px;
            cursor: pointer;
        }


    </style>
{% endblock %}

templates/reservation/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reservation index{% endblock %}

{% block body %}

    <div class="breadcrumbs">
        <div class="page-header d-flex align-items-center"
             style="background-image: url('../frontOffice/assets/img/page-header.jpg');">
            <div class="container position-relative">
                <div class="row d-flex justify-content-center">
                    <div class="col-lg-6 text-center">
                        <h2>Reservation</h2>
                        <p></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <h1>Reservation pour l'evenement {{ event.nom }}  {{ app.user.id}} {{app.user.nom}}</h1>
    <a href="{{ path('app_reservation_new') }}">Create new</a>
{% endblock %}

templates/reservation/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Reservation{% endblock %}

{% block body %}
    <style>
        .mt-5{
            margin-top: 100px !important;
            width: 50%;
            margin-left: 250px;
            margin-right: 150px;
        }
    </style>
    <div class="mt-5">
         {{ include('reservation/_form.html.twig') }}
    </div>
{% endblock %}

templates/reservation/next.html.twig
{% extends 'base.html.twig' %}

{% block title %}Pick Your Ticket{% endblock %}

{% block body %}
    <label style="color: dodgerblue; margin-top: 120px; margin-left: 60px ;font-size: 47px">Pick your ticket :</label>
    <style>@import url('https://fonts.googleapis.com/css?family=Oswald');
        * {
            margin: 0;
            padding: 0;
            border: 0;
            box-sizing: border-box
        }

        body {
            background-color: #dadde6;
            font-family: arial
        }

        .fl-left {
            float: left
        }

        .fl-right {
            float: right
        }

        h1 {
            text-transform: uppercase;
            font-weight: 900;
            border-left: 10px solid #fec500;
            padding-left: 10px;
            margin-bottom: 30px
        }

        .row {
            overflow: hidden
        }

        .card {
            display: block;
            width: 750px;
            height: 340px;
            background-color: white;
            color: #989898;
            margin-bottom: 10px;
            font-family: 'Oswald', sans-serif;
            text-transform: uppercase;
            border-radius: 4px;
            position: relative;

        }

        .card+.card {
            margin-left: 2%
        }

        .date {
            display: table-cell;
            width: 25%;
            position: relative;
            text-align: center;
            border-right: 2px dashed #dadde6
        }

        .date:before,
        .date:after {
            content: "";
            display: block;
            width: 30px;
            height: 30px;
            background-color: #DADDE6;
            position: absolute;
            top: -15px;
            right: -15px;
            z-index: 1;
            border-radius: 50%
        }

        .date:after {
            top: auto;
            bottom: -15px
        }

        .date time {
            display: block;
            position: absolute;
            top: 50%;
            left: 50%;
            -webkit-transform: translate(-50%, -50%);
            -ms-transform: translate(-50%, -50%);
            transform: translate(-50%, -50%)
        }

        .date time span {
            display: block
        }

        .date time span:first-child {
            color: #2b2b2b;
            font-weight: 600;
            font-size: 250%
        }

        .date time span:last-child {
            text-transform: uppercase;
            font-weight: 600;
            margin-top: -10px
        }

        .card-cont {
            display: table-cell;
            margin: auto;
            font-size: 85%;
            padding-left: 13px;
            padding-top: 54px;
        }

        .card-cont h3 {
            color: #3C3C3C;
            font-size: 130%
        }

        .row:last-child .card:last-of-type .card-cont h3 {
            text-decoration: line-through
        }

        .card-cont>div {
            display: table-row
        }

        .card-cont .even-date i,
        .card-cont .even-info i,
        .card-cont .even-date time,
        .card-cont .even-info p {
            display: table-cell;
        }

        .card-cont .even-date i,
        .card-cont .even-info i {
            padding: 5% 5% 0 0
        }

        .card-cont .even-info p {
            padding: 5px 74px 0 0;
        }

        .card-cont .even-date time span {
            display: block
        }

        .card-cont a {
            display: block;
            text-decoration: none;
            width: 80px;
            height: 30px;
            background-color: #D8DDE0;
            color: #fff;
            text-align: center;
            line-height: 30px;
            border-radius: 2px;
            position: absolute;
            right: 10px;
            bottom: 10px
        }

        .row:last-child .card:first-child .card-cont a {
            background-color: #037FDD
        }

        .row:last-child .card:last-child .card-cont a {
            background-color: #F8504C
        }

        @media screen and (max-width: 860px) {
            .card {
                display: block;
                float: none;
                width: 100%;
                margin-bottom: 10px
            }
            .card+.card {
                margin-left: 0
            }
            .card-cont .even-date,
            .card-cont .even-info {
                font-size: 75%
            }
        }
    </style>
    <form method="POST" action="{{ path('app_ticket', {'reservationId': reservation.id, 'eventId': eventId}) }}" >
        {% for type, messages in app.session.flashbag.all() %}
            {% for message in messages %}
                <div class="alert alert-warning" role="alert">
                    {{ message }}
                </div>
            {% endfor %}
        {% endfor %}
        {% for billet in billets %}
            <section class="container">
                <div style="display: flex">
                <article class="card fl-left flex">
                    <section class="date">
                        <time>
                            <span>{{ billet.dateValidite ? billet.dateValidite|date('d') : '' }}</span>
                            <span>{{ billet.dateValidite ? billet.dateValidite|date('F') : '' }}</span>
                        </time>
                    </section>
                    <section class="card-cont" >
                        <h3 style="margin-top: -999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999%">{{ billet.evenement.nom }}</h3>
                        <small>{{ billet.evenement.createur.nom }}</small>
                        <h3>live In {{ billet.evenement.addresse }}</h3>
                        <div class="even-date">
                            <i class="fa fa-calendar"></i>
                            <time>
                                <span>{{ billet.dateValidite ? billet.dateValidite|date('Y-m-d') : '' }}</span>
                                <span> Debut: 8:00 - Fin: 17:55 </span>
                            </time>
                        </div>
                        <div class="even-info">
                            <i class="fa fa-map-marker"></i>
                            <p>
                                {{ billet.evenement.addresse }}
                            </p>
                        </div>
                        <label style="color: dodgerblue;float: right; margin-right: 47%;">{{ billet.type }} : {{ billet.prix }} DT</label><br><br>
                        <div style="font-size: 60%;">for any information contact us on 74 800 008 or on 21 080 080 </div>
                    </section>
                    <section class="card-cont" >
                        <img src="{{ qrCodeTable[loop.index0] }}" alt="QR code" style="width: 150px;height: 150px;float: right;margin-right: 20px;">
                    </section>
                </article>
                    <input type="number" class="form-control text-center" name="{{ billet.type }}" value="0" min="0" style="width: 70px;
                     height: 40px; margin-top: 135px;margin-left: 100px">
                </div>
            </section>

        {% endfor %}
        <button type="submit" class="btn btn-primary btn-lg active float-right" style="margin-left: 100px;margin-bottom: 40px">Submit</button>
    </form>
{% endblock %}

templates/reservation/show.html.twig
s{% extends 'base.html.twig' %}

{% block title %}Reservation{% endblock %}

{% block body %}
    <h1>Reservation</h1>
{#to be fixed#}
    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ reservation.id }}</td>
            </tr>
            <tr>
                <th>DateReservation</th>
                <td>{{ reservation.dateReservation ? reservation.dateReservation|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Status</th>
                <td>{{ reservation.status }}</td>
            </tr>
            <tr>
                <th>PaymentInfo</th>
                <td>{{ reservation.paymentInfo }}</td>
            </tr>
            <tr>
                <th>TotalPrice</th>
                <td>{{ reservation.totalPrice }}</td>
            </tr>
            <tr>
                <th>PaymentStatus</th>
                <td>{{ reservation.paymentStatus }}</td>
            </tr>
            <tr>
                <th>NbrBillets</th>
                <td>{{ reservation.nbrBillets }}</td>
            </tr>
            <tr>
                <th>NbrTicketType1Reserved</th>
                <td>{{ reservation.nbrTicketType1Reserved }}</td>
            </tr>
            <tr>
                <th>NbrTicketType2Reserved</th>
                <td>{{ reservation.nbrTicketType2Reserved }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_reservation_index') }}">back to list</a>

    <a href="{{ path('app_reservation_edit', {'id': reservation.id}) }}">edit</a>

    {{ include('reservation/_delete_form.html.twig') }}
{% endblock %}